# Generated by Django 4.2.3 on 2023-08-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_compra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
