# Generated by Django 4.2.3 on 2023-08-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_delete_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='canidad',
            new_name='cantidad',
        ),
    ]
