# Generated by Django 4.2.3 on 2023-08-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_producto_compra_fruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruta', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Panaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('peso', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Compra',
            new_name='Carniceria',
        ),
        migrations.RenameField(
            model_name='carniceria',
            old_name='fruta',
            new_name='carne',
        ),
    ]
