# Generated by Django 4.2.3 on 2023-08-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_fruta_panaderia_rename_compra_carniceria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carniceria',
        ),
        migrations.DeleteModel(
            name='Panaderia',
        ),
    ]
