# Generated by Django 4.2.3 on 2023-08-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_delete_carniceria_delete_panaderia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carniceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carne', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Panaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('peso', models.CharField(max_length=100)),
            ],
        ),
    ]
