# Generated by Django 4.2.3 on 2023-08-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_carniceria_panaderia'),
    ]

    operations = [
        migrations.AddField(
            model_name='carniceria',
            name='peso',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AddField(
            model_name='fruta',
            name='peso',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='panaderia',
            name='peso',
            field=models.CharField(default='0.0', max_length=100),
        ),
    ]
