# Generated by Django 4.2.3 on 2023-08-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_carniceria_peso_fruta_peso_alter_panaderia_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='clave',
            field=models.CharField(max_length=100),
        ),
    ]
