# Generated by Django 4.2.3 on 2023-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_ingreso_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
