# Generated by Django 4.2.3 on 2023-08-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_fruta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carniceria',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='panaderia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
